spring:
  application:
    name: dsprocessfailureconsumer
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        concurrency: 2
        max-concurrency: 10
        prefetch: 1
      
server:
  port: 0
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8190/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90  
        
proserv:
  dsappdata:
    username: docusignuser
    password: testing1
  dsauthentication:
    username: docusignuser
    password: testing1
  dscachedata:
    username: docusignuser
    password: testing1
  dscoredata:
    username: docusignuser
    password: testing1
  dsenvelopedata:
    username: docusignuser
    password: testing1  
  dsreportdata:
    username: docusignuser
    password: testing1  
  application:
    username: docusignuser
    password: testing1
  queue: 
    name: CORE_PARALLEL_PROCESS_FAILURE_QUEUE
    ttl: 2000
  exchange:
    name: MIGRATION_EXCHANGE
  routing:
    key: CORE_PARALLEL_PROCESS_FAILURE_QUEUE
  processstart:
    queuename: CORE_PARALLEL_PROCESS_START_QUEUE
  processfailure:
    queuename: CORE_PARALLEL_PROCESS_FAILURE_QUEUE
    queue:
      failure:
        retrylimit: 5
  processcomplete:
    queuename: CORE_PARALLEL_PROCESS_END_QUEUE
  reportcomplete: 
    queuename: CORE_PARALLEL_REPORT_COMPLETE_QUEUE
  reportdata: 
    queuename: CORE_PARALLEL_REPORT_DATA_QUEUE
  cacheevict: 
    queuename: CORE_CACHEEVICT_QUEUE
  docdownload: 
    queuename: CORE_PARALLEL_DOC_DOWNLOAD_QUEUE
  process: 
    startbyqueue: 
    failurebyqueue: 
    reportdatabyqueue: 
  crud: 
    authbyclient:
    cachebyclient: 
    reportbyclient: 
    failurebyclient: 
    completebyclient:       
       
ds:
  propertycache:
    cacheexpirationseconds: 1800
  cachenames: \"token\", \"baseUrl\", \"propertyCache\"
         
dscoredata:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1200
    ConnectTimeout: 30000
    ReadTimeout: 30000

dscachedata:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1200
    ConnectTimeout: 30000
    ReadTimeout: 30000
    
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"