spring:
  application:
    name: dsreportdatashell
  profiles:
     active: dev
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=ihdadb
    username: sa
    password: DocuSign1!
    hikari:
      maximum-pool-size: 10
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 3600000

spring.jpa.properties.hibernate.generate_statistics: true
spring.jpa.properties.hibernate.jdbc.batch_size: 200
spring.jpa.properties.hibernate.order_inserts: true
spring.jpa.properties.hibernate.order_updates: true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.cache.use_second_level_cache: true
spring.jpa.hibernate.cache.use_query_cache: true
spring.jpa.hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8190/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    
shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED
              
app:
   esignAPIVersion: v2.1
   clickAPIVersion: v1
   roomsAPIVersion: v2
   clmAPIVersion: v201411
   clmAuthAPIVersion: v201606
   clickAPIEndPoint: clickapi
   clmAPIUserEndPoint: apiuser
   esignAPIAccountUsersEndpoint: users
   esignAPIDocumentsEndpoint: documents
   orgAdminAPIBaseUrl: https://api-d.docusign.net/management/v2/organizations
   roomsAPIBaseUrl: https://demo.rooms.docusign.com/restapi
   clmAPIBaseUrl: https://apina11.springcm.com
   clmAuthAPIBaseUrl: https://authuat.springcm.com/api
   totalRowsPerProcess: 100
   apiThresholdLimitPercent: 20
   ruleEngineJsonFilePath: src/test/resources/config/ruleEngine.json
   createTablesJsonFilePath: src/test/resources/config/createTables.json
   async:
        executornameprefix: DSExecutor-
        corepoolsize: 10
        maxpoolsize: 50
        queuecapacity: 9999999
   db:
     auditorname: ReportApp
   authorization:
     rsaPrivateKeyPath: ${configPath}\\ds-private.key
     rsaPublicKeyPath: ${configPath}\\ds-public.key
     aud: account-d.docusign.com
     integratorKey: 4a571161-05ee-4812-83d0-da7ff5c2eab9
     scopes: impersonation signature organization_read permission_read domain_read user_read user_write
     userId: 51828699-9931-49e9-8426-79dcf3796dd3
     token:
           expirationSeconds: 3600
           cacheExpirationSeconds: 1800
           
proserv:
  dsappdata:
    username: docusignuser
    password: testing1
  dsauthentication:
    username: docusignuser
    password: testing1
  dscachedata:
    username: docusignuser
    password: testing1
  dscoredata:
    username: docusignuser
    password: testing1
  dsenvelopedata:
    username: docusignuser
    password: testing1  
  dsreportdata:
    username: docusignuser
    password: testing1  
  application:
    username: docusignuser
    password: testing1
  processstart:
    queuename: CORE_PARALLEL_PROCESS_START_QUEUE
  processfailure:
    queuename: CORE_PARALLEL_PROCESS_FAILURE_QUEUE
  processcomplete:
    queuename: CORE_PARALLEL_PROCESS_END_QUEUE
  reportdata: 
    queuename: CORE_PARALLEL_REPORT_DATA_QUEUE
  docdownload: 
    queuename: CORE_PARALLEL_DOC_DOWNLOAD_QUEUE
  process: 
    startbyqueue: 
    failurebyqueue: 
    reportdatabyqueue:
    docdownloadbyqueue:  
  crud: 
    authbyclient:
    cachebyclient: 
    reportbyclient: 
    failurebyclient: 
    completebyclient:  
    
ds:
  propertycache:
    cacheexpirationseconds: 1800
  cachenames: \"token\", \"baseUrl\", \"propertyCache\"
  
dsreportdata:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1200
    ConnectTimeout: 30000
    ReadTimeout: 30000

dscachedata:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1200
    ConnectTimeout: 30000
    ReadTimeout: 30000
    
dscoredata:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1200
    ConnectTimeout: 30000
    ReadTimeout: 30000   
    
dsauthentication:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1200
    ConnectTimeout: 30000
    ReadTimeout: 30000    