package com.ds.proserv.common.constant;

public enum QueryOption {

	FETCHLASTBATCHBYTYPE, 
	FETCHALLTHREADSBYID, 
	FETCHALLINCOMPLETEBATCHES,
	FETCHALLACCOUNTSTOTALCOUNTBYID, 
	CLOSELASTRUNNINGBATCHID,
	FETCHALLFAILURESBYBATCHID,
	RETRYFAILEDBATCHID,
	RUNONDEMANDQUERY,
	SAVETOOLEXPIRY;
}